[dependencies]
base = "0.11.1"
matchers = "https://github.com/kritzcreek/motoko-matchers#3dac8a071b69e4e651b25a7d9683fe831eb7cffd@3dac8a071b69e4e651b25a7d9683fe831eb7cffd"
icrc1 = "0.0.2"
ledger-types = "1.0.0"
"principal.mo" = "https://github.com/aviate-labs/principal.mo#master@c65c1da072cdc8066352ad29b56c39cde2af2a0b"
motoko-hash-map = "https://github.com/ZhenyaUsenko/motoko-hash-map#master@94d509f97d70ac03828eee3064d939a3259eab78"
map = "9.0.1"
prng = "0.0.3"
fuzz = "0.2.1"
xtended-text = "0.2.5"
vector = "0.3.1"
xtended-numbers = "0.2.1"
icrc3-mo = "0.2.6"
cert = "https://github.com/nomeata/ic-certification#v0.1.3"
stable-rbtree = "1.0.0"
stable-buffer = "1.0.1"
stableheapbtreemap = "1.5.0"